#!/bin/bash

# Apply Message Batching and Handoff Reduction Fixes
# Run this script to update the AI system prompt in Supabase

echo "================================================"
echo "Message Batching & Handoff Reduction Fix"
echo "================================================"
echo ""
echo "This will update your AI system prompt to:"
echo "1. Reduce unnecessary handoffs to John"
echo "2. Make AI more confident in handling queries"
echo ""
echo "The message batching code is already in place."
echo ""
echo "To apply the system prompt update:"
echo ""
echo "Option 1 - Via Supabase SQL Editor:"
echo "  1. Open Supabase Dashboard"
echo "  2. Go to SQL Editor"
echo "  3. Copy and paste contents of: update-system-prompt-reduce-handoffs.sql"
echo "  4. Click Run"
echo ""
echo "Option 2 - Via psql (if configured):"
echo "  psql \$DATABASE_URL -f update-system-prompt-reduce-handoffs.sql"
echo ""
echo "Option 3 - Via Settings Page:"
echo "  1. Go to your dashboard Settings page"
echo "  2. Update the System Prompt field"
echo "  3. Copy the prompt from update-system-prompt-reduce-handoffs.sql"
echo ""
echo "================================================"
echo "After applying, test with:"
echo "================================================"
echo ""
echo "Test 1 - Rapid Messages:"
echo "  Send 3-4 quick SMS messages"
echo "  Expected: Single comprehensive response"
echo ""
echo "Test 2 - Standard Queries (should NOT pass to John):"
echo "  - 'How much for iPhone screen repair?'"
echo "  - 'Do you buy phones?'"
echo "  - 'What are your hours?'"
echo "  - 'Got any cases?'"
echo ""
echo "Test 3 - Escalation Queries (should pass to John):"
echo "  - 'Can I speak to the owner?'"
echo "  - 'I want to complain about...'"
echo ""
echo "================================================"
echo "See MESSAGE_BATCHING_AND_HANDOFF_FIX.md for details"
echo "================================================"
